### ISSUE TITLE
Low prio: README has wrong installation instructions

### ISSUE THREAD

**Issue by kgrossjo** [ats/atom.mmbundle#1]
The readme says I can "install" this bundle by going to the Bundles tab in the preferences.  But that's not how it works.  I have to

```
mkdir -p ~/Library/Application\ Support/MailMate/Bundles
cd ~/Library/Application\ Support/MailMate/Bundles
git clone https://github.com/ats/atom.mmbundle
```

... and then restart Atom.

(Note that there was a slight typo in the mailing list thread which mentioned `~/Application Support/` instead of `~/Library/Application Support/`.)

Hm.  I guess the instructions will have to change again when the bundle is incorporated into the "official" distribution, but I have no idea how or when that happens...

**Comment by ats** [comment]
Yep, you're right on both counts: the mail thread mistakenly left out the `Application Support` part of the path, and the readme is just copied from an existing bundle. I think Benny plans to incorporate this into the official distribution, though like you I don't know when.

I can temporarily change the readme for now. To clarify how you installed it, did you only check it out to your Bundles directory? I was under the impression that it had to be in the Managed/bundles directory before MailMate would recognize it in the "local" Bundles dir.

Thanks

-Alan

**Comment by kgrossjo** [comment]
I never touched the `Managed/Bundles` directory, it's only under the 
`Bundles` directory that I had to create first.  The following shell 
snippet should explain unambiguously:

```
$ find ~/Library/Application\ Support/MailMate -iname '*atom*' | sed -e 
```

"s/$USER/\$USER/g"
    /Users/$USER/Library/Application Support/MailMate/Bundles/atom.mmbundle

Thank you for your work!

Kai

**Comment by ats** [comment]
Thanks for clarifying. I've updated the readme accordingly. If/when it 
goes into the official repository, we'll change it again.

Thanks,
Alan
